// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

// eslint-disable-next-line @typescript-eslint/no-empty-interface,@typescript-eslint/no-empty-object-type
interface Env {
  DB: D1Database
  KV: KVNamespace
  ENV: string
  JWT_SECRET: string
  CRYPTO_IV: string
  ENC_KEY: string
  CLIENT_ID: string
  REDIRECT_URI: string
  CLIENT_SECRET: string
  FRONTEND_HOST: string
  GATEWAY_COMMUNICATOR_HOST: string
  GATEWAY_COMMUNICATOR_SECRET: string
}
