// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

// eslint-disable-next-line @typescript-eslint/no-empty-interface,@typescript-eslint/no-empty-object-type
interface Env {
  ENV: string
  DB: D1Database
  JWT_SECRET: string
  CRYPTO_IV: string
  ENC_KEY: string
}
