#:schema node_modules/wrangler/config-schema.json
name = "gateway-app"
main = "src/worker.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm install"

[env.development]
d1_databases = [{ binding = "DB", database_name = "gateway", database_id = "0086ba47-debb-4c13-8a69-318c2b9127db" }]
kv_namespaces = [{ binding = "KV", id = "44982c3712ee40b1b7fc5d8d1bafe5c8" }]

[env.production]
name = "gateway-app"
d1_databases = [{ binding = "DB", database_name = "gateway", database_id = "db-id" }]
kv_namespaces = [{ binding = "KV", id = "production_kv_namespace_id" }]
